Models/Job.cs
namespace Worktastic.Models
{
    public class Job
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Company Company { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public int? Salary { get; set; }
        public DateTime? StartDate { get; set; }
        public TimeSpan? Duration { get; set; }


        public override bool Equals(object? obj)
        {
            return obj is Job job &&
                   Id == job.Id &&
                   Title == job.Title &&
                   Description == job.Description &&
                   EqualityComparer<Company>.Default.Equals(Company, job.Company) &&
                   Location == job.Location &&
                   Type == job.Type &&
                   Category == job.Category &&
                   Salary == job.Salary &&
                   StartDate == job.StartDate &&
                   EqualityComparer<TimeSpan?>.Default.Equals(Duration, job.Duration);
        }

        public override int GetHashCode()
        {
            HashCode hash = new HashCode();
            hash.Add(Id);
            hash.Add(Title);
            hash.Add(Description);
            hash.Add(Company);
            hash.Add(Location);
            hash.Add(Type);
            hash.Add(Category);
            hash.Add(Salary);
            hash.Add(StartDate);
            hash.Add(Duration);
            return hash.ToHashCode();
        }
    }
}

Controllers/JobController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using Worktastic.Data;
using Worktastic.Models;

namespace Worktastic.Controllers
{
    [Authorize]
    public class JobController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public JobController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (!user.IsCompanyAccount)
            {
                return Unauthorized();
            }

            Company company = _context.Companies.SingleOrDefault(x => x.User == user);

            if(company == null)
            {
                return NotFound();
            }

            List<Job> jobs = _context.Jobs.Where(x => x.Company.Id == company.Id).ToList();

            return View(jobs);
        }

        public async Task<IActionResult> New()
        {
            var user = await _userManager.GetUserAsync(User);
            if (!user.IsCompanyAccount)
            {
                return Unauthorized();
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Job newJob)
        {
            var user = await _userManager.GetUserAsync(User);
            if (!user.IsCompanyAccount)
            {
                return Unauthorized();
            }

            Company company = _context.Companies.SingleOrDefault(x => x.User == user);
            if(company == null)
            {
                return RedirectToAction("New", "Company");
            }

            newJob.Company = company;

            _context.Add(newJob);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var job = _context.Jobs.
                Include(j => j.Company).
                Include(j => j.Company.User).
                SingleOrDefault(j => j.Id == id);

            if (job == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            if (!job.Company.User.Equals(user))
            {
                return Unauthorized();
            }

            return View(job);
        }

        [HttpPost]
        public IActionResult Update(Job job)
        {
            try
            {
                _context.Jobs.Update(job);
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return NotFound();
            }

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            if (id == 0) return BadRequest();

            Job job = _context.Jobs.SingleOrDefault(x => x.Id == id);

            if (job == null) return NotFound();

            _context.Jobs.Remove(job);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Job/Edit.cshtml
@model Worktastic.Models.Job;
@{
    ViewData["Title"] = "Create Job";
}

<form class="mt-5" asp-controller="Job" asp-action="Update" formmethod="post">
    <div class="card">
        <div class="card-header">
            <h4>Create Job</h4>
        </div>
        <div class="card-body">
            <input hidden asp-for="Id" />
            <div class="row form">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control " asp-for="Title" type="text" id="form-title" placeholder="Title" required />
                        <label for="form-title">Title</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <textarea class="form-control" placeholder="Description" id="form-description" asp-for="Description" style="height: 150px" required></textarea>
                        <label for="form-description">Description</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Location" type="text" id="form-location" placeholder="Location" required />
                        <label for="form-location">Location</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Type" type="text" id="form-type" placeholder="Type" required />
                        <label for="form-type">Type</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Category" type="text" id="form-category" placeholder="Category" />
                        <label for="form-category">Category</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Salary" type="number" id="form-salary" placeholder="Salary in €" />
                        <label for="form-salary">Salary in €</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="StartDate" type="text" onfocus="(this.type='date')" onblur="if(!this.value)this.type='text'" id="form-starting-date" placeholder="Starting Date" />
                        <label for="form-starting-date">Starting Date</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Duration" type="datetime" id="form-duration" placeholder="Duration" />
                        <label for="form-duration">Duration</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer container">
            <div class="row justify-content-between">
                <div class="btn-group col-1">
                    <button class="btn btn-primary" type="submit">Update</button>
                    <button class="btn btn-outline-success" type="reset">Reset</button>
                </div>
                <div class="col-2 d-flex justify-content-end">
                    <a class="btn btn-secondary align-self-end" href="javascript:history.go(-1)">Back</a>
                </div>
            </div>
        </div>
    </div>
</form>

Views/Job/Index.cshtml
@model List<Worktastic.Models.Job>;
@{
    ViewData["Title"] = "Job";
}

<h1>Job Page</h1>
<hr/>
<a class="btn btn-primary mb-3" asp-controller="Job" asp-action="New">Create Job</a>

<table id="jobTable" class="table table-bordered table-hover table-striped">
    <thead class="table-secondary">
        <tr class="mt-2">
            <th>Title</th>
            <th>Description</th>
            <th>Company</th>
            <th>Location</th>
            <th>Type</th>
            <th>Category</th>
            <th>Salary</th>
            <th>StartDate</th>
            <th>Duration</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach(var job in Model)
            {
                <tr>
                    <td>@job.Title</td>
                    <td>@job.Description</td>
                    <td>@job.Company.Name</td>
                    <td>@job.Location</td>
                    <td>@job.Type</td>
                    <td>@job.Category</td>
                    <td>@job.Salary</td>
                    @if(@job.StartDate != null){ <td>@job.StartDate.Value.ToShortDateString()</td> }
                    else{ <td></td> }
                    <td>@job.Duration</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-warning" asp-route-id="@job.Id" asp-controller="Job" asp-action="Edit">Edit</a>
                            <!--<a class="btn btn-danger" asp-route-id="@job.Id" asp-action="Delete" asp-controller="Job">Delete</a>-->
                            <button class="btn btn-danger" onclick="onDelete(@job.Id)">Delete</button>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<div class="col-auto d-flex justify-content-end">
    <a class="btn btn-secondary align-self-end mt-3" asp-controller="Company" asp-action="Index">Back</a>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#jobTable').DataTable();
        });


        function onDelete(id) {
            Swal.fire({
                title: 'You want to delete this Job post?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            })
            .then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: "@Url.Action("Delete")",
                        data: {
                            id: id
                        },
                        type: 'DELETE',
                        success: function (msg) {
                            Swal.fire(
                                'Deleted!',
                                'Your Post has been deleted.',
                                'success'
                            )
                            .then(result => {
                                location.reload();
                            });
                        },
                        error: function (msg) {
                            Swal.fire(
                                'Error!',
                                'Something went wrong.',
                                'error'
                            )
                        }
                    });
                }
            })
        }
    </script>
}

Views/Job/New.cshtml
@model Worktastic.Models.Job;
@{
    ViewData["Title"] = "Create Job";
}

<form asp-controller="Job" asp-action="Create" formmethod="post">
    <div class="card">
        <div class="card-header">
            <h4>Create Job</h4>
        </div>
        <div class="card-body">
            <input hidden asp-for="Id" />
            <div class="row form">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control " asp-for="Title" type="text" id="form-title" placeholder="Title" required />
                        <label for="form-title">Title</label>
                    </div>
                </div> 
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <textarea class="form-control" placeholder="Description" id="form-description" asp-for="Description" style="height: 150px"></textarea>
                        <label for="form-description">Description</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Location" type="text" id="form-location" placeholder="Location" required />
                        <label for="form-location">Location</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Type" type="text" id="form-type" placeholder="Type" required />
                        <label for="form-type">Type</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Category" type="text" id="form-category" placeholder="Category" />
                        <label for="form-category">Category</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Salary" type="number" id="form-salary" placeholder="Salary in €" />                        
                        <label for="form-salary">Salary in €</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-floating mb-3">                        
                        <input class="form-control" asp-for="StartDate" type="text" onfocus="(this.type='date')" onblur="if(!this.value)this.type='text'" id="form-starting-date" placeholder="Starting Date" />
                        <label for="form-starting-date">Starting Date</label>
                    </div>                    
                </div>    
                <div class="col">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Duration" type="datetime" id="form-duration" placeholder="Duration" />
                        <label for="form-duration">Duration</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button class="btn btn-primary" type="submit">Create</button>
            <button class="btn btn-secondary" type="reset">Reset</button>
        </div>
    </div>
</form>